# Generated by Django 3.2 on 2022-04-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followsystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
